### ISSUE TITLE
Super big wide GoBack button for efficient

### ISSUE THREAD

**Issue by ugotta** [perfect-things/perfect-home#112]
1. Super wide full width translucent top "go back" button: Very easy to click, very efficient.
css: `.icon-btn.btn-back {
width: 100%;
text-align: left;
height: 50px;
border-radius: 6px;
background: #0000003d;
}`
**If possible, press and hold the left button, or right-click, and the GoBack button becomes a search bar:**
Type some keywords: filter in current folder;
Then hit enter or search button: search all;

2. #107 It is strongly recommended that the animation time can be customized, do not let the eyes wait.

3. Remember the last open folder.

4.  If the bookmark title is very long, the docked folder will overflow on the far right.
fix `.folder {
    overflow: hidden;
}`

5. The dock folder is very good. But we can also consider: At the top or side also, add the Favor folder.

6. Display the title in the middle of the folder icon instead of at the bottom: optional

7. There's another pattern that may be very useful: **the folder list at the top, and the bookmark link list below**.
This requires a flat, compact layout, and you can't drag to adjust the order. 
If possible, remember the state of each folder (you can switch easily, such as double clicking on the background), or at least in the root directory.

8.  Click into a folder, if the scroll bar appears, should avoid shaking left and right.

**Comment by tborychowski** [comment]
Thanks very much for a thorough review & for the feedback!

As for your comments:

**1.** This is exactly the reason why "Custom CSS" (in Settings) is for! (it may not work for you ATM, depending on the Firefox version, due to [this bug](#113)).
- You can add this CSS in settings and it will work like that for you. Please consult the [customization tutorial](https://github.com/perfect-things/perfect-home/blob/master/customization-tutorial.md).
- If you wish to have it available in an easier way - you can submit a PR to the [themes](https://github.com/perfect-things/perfect-home-themes) repo and - once merged - it will be available as a Theme in Settings.
- Lastly - to go back to the parent folder you can click browser's back button (or use mouse buttons or gestures).

>If possible, press and hold the left button, or right-click, and the GoBack button becomes a search bar:
>Type some keywords: filter in current folder;
>Then hit enter or search button: search all;

Sorry, but it may sound useful to you (especially if you're used to UIs designed by developers), but it's really poor UX!
- buttons should most definitely not change into inputs. UI elements should remain consistent and not move around depending on how long you press a button.
- filtering should be consistent and produce the same results, no matter where you are or what you press.

You have the command-palette/search box that filters through all your bookmarks. There is no search, because we're not searching anything. We have a finite list of bookmarks that we can only filter. 


**2.** Yep. This is on the "Next up" list and will be added to the next release. 

**3.** Not sure what you mean by that.
If you select a folder as the "Main folder" - it will always be opened when you open the page.
If you enter a folder and e.g. refresh the page - you will stay in that folder (contrary to many other SpeedDial extensions)
If you enter a folder and open a bookmark and then click Browser's Back button - you will also return to the last folder you were in.
Anything more would probably be confusing.

**4.**  This is a good idea, thanks, I will add it! (https://github.com/perfect-things/perfect-home/issues/114)

**5.** Please have a look at the [customization tutorial](https://github.com/perfect-things/perfect-home/blob/master/customization-tutorial.md) and let me know if this is sufficient for you.
I'd like to keep the UI & settings simple enough, so that less technical people can easily handle it too, and in the same time - allow the more tech savvy customize the crap out of it :-)

**6.** This is exactly how it shows up when you flip the switch (in Settings) called "Show labels": if the labels are hidden - folder labels will show up on the icon. But if the labels are visible - the folders need to show some text, so having the label on the icon and below it would be weird :-)

**7.** Yeah.... No :-) I want by bookmarks ordered exactly like I want them ordered. And at least 500 other people using that extension. What you're suggesting would be really weird and confusing :-)

**8.** Sorry, but I have no idea what you mean here. I don't see any shaking or anything. Could you explain this in more details (or - ideally - record a gif?)

Thanks again!

**Comment by ugotta** [comment]
**3.** Remember the last open folder.

Click into a folder Bookmark/folderA/folderB
Next time start Perfect Home, should stay in Bookmark/folderA/folderB
In this way, I can continue to do related things in the same folder.
Current always go main folder Bookmark/

**1.** Then again, why a super full wide "go back" button is needed. `.icon-btn.btn-back { width: 100%; text-align: left; height: 50px; border-radius: 6px; background: #0000003d; }`
I just need to move the mouse up and I can easily click it, instead of having to move the mouse to aim at a small button. You know, it can take hundreds of times a day to find a forgotten bookmark. I have more than 1000 bookmarks, which are still increasing. There are many level 3 folders. I can't remember so many names. I may have to go back and forth to some folders to find them.
Maybe it doesn't conform to the UI aesthetic, so I'll use it myself.

**6.** It might break the UI
 `.item-thumb + .item-title {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    font-weight: 300;
    font-size: large;
}`

**7.** Please refer to the **Bookdial** extension. Absorb the useful parts

The most important thing is super Full Wide GO Back Button. I think it will be very popular with users. 
Other suggestions may not be for everyone.

**Comment by tborychowski** [comment]
Hi Again,

**3.** I understand now what you mean. I can consider adding a setting for that (https://github.com/perfect-things/perfect-home/issues/115).

**6.** I didn't mean to style it yourself. You can just hide labels for bookmarks (in Settings/Customize section), and the folder labels then will show up on folders. There's a script that will make sure (as best as possible) that label fits within the folder icon. Here's how it works:
![thumb](https://user-images.githubusercontent.com/392513/97297033-61f41f00-1849-11eb-9c29-0a40a33a41e4.png).

**7.** I checked out the extension you mentioned and didn't like it (for many reasons). It's clearly a different solution (for a similar problem) and with different goals. I've been working on my extension for the past year and before that had another similar extension for a year or so, and all that experience together with the feedback from many users went into the design of the current state this extension is in. I'm sorry if you don't like some features, but it's impossible for any product to meet all users' needs 😄 
I'm trying my best to make it as universal as possible, maintaining the good UX (dictated by the 20yrs of my professional experience) and simplicity.


On top of that - every single option/settings increases the complexity and the maintenance of the extension, and for me this means that I will have to put more of my time to develop new features, making sure that all of the old ones still work (testing them manually every time, as there is no way to automate end-to-end tests for a firefox extension AFAIK).
So to me - adding a new thing - is also a commitment that from now on I will be supporting this feature/option/etc. and I can only spare so much of my time of my life, working on this :-)
That's why I've added the possibility for users to "hack it" if they want to :-)
And that's why - a lot of the times - I will have to tell people "no" to their feature requests, if they don't fit my design & plan for this little project :-)

I hope you understand my point and forgive me, if I can't make you 100% happy :-)

**Comment by tborychowski** [comment]
I've released a new version with bug fixes and new features (including some that you have suggested here).
Please feel free to re-open (or create a new issue) if you wish to discuss further, or have some other suggestions/feedback :-)
Thanks!
