### ISSUE TITLE
Feature Request:  bookmark "Separator" = line-return

### ISSUE THREAD

**Issue by barnscott** [perfect-things/perfect-home#3]
In Firefox, user can create "New Separator". It would be great if Firefox bookmark separator would provide a line-return (next row) on the "perfect-home" so that I can better organize bookmarks.

**Comment by tborychowski** [comment]
Hi,
Thanks for testing the beta, and thanks for reporting the issue.

This request is a bit tricky to do.
Let me explain why:
- currently the addon reads the list of bookmarks and outputs them as a flat list 
- separators appear as empty tiles
- the layout is using the css grid 
- the layout is responsive, so if you resize the browser to be smaller -  tiles get smaller and eventually they wrap

Because the css grid does not allow line returns  and because it's responsive (wraps on smaller screens) - to add a line return - the layout would have to be recalculated every time you  resize the browser, and instead of css - use javascript, which is not the best practice and would affect the performance of the whole thing.
It would also add a lot of complexity, and maintenance cost, which I'm trying to avoid.

There are some other features planned, that maybe will help better organise the bookmarks on the page, but unfortunately line returns are out of scope at this time.

As a workaround you can add multiple separators so that they fill the row in your bookmarks, so that they look like a line-break.
