### ISSUE TITLE
Suggestion: tile image improvements

### ISSUE THREAD

**Issue by HanabishiRecca** [perfect-things/perfect-home#37]
Suggestions:
1. Ability to set "auto" tile image mode (works like it was in "newtab-bookmarks")
2. Ability to set tile image via url

**Comment by tborychowski** [comment]
1. Not sure what do you mean by "auto". If it means - fetch the favicon, than no - that's not gonna happen. This is the reason why I'm abandoning the previous addon. 
This requires a 3rd party service and there's no good enough, free, reliable and future proof service that would do that.

2. That's a great idea and I will implement that in the next release. Thanks! 😄

**Comment by HanabishiRecca** [comment]
@tborychowski how about to use this service https://api.faviconkit.com/twitter.com/256

Or maybe allow user to set custom template in options.
For example:
`https://api.faviconkit.com/${domain}/256`

**Comment by tborychowski** [comment]
Yes, I've checked this out before.
The "Join the beta" button doesn't do anything...

Also they rate-limit (so if you request too many times in a short period of time - you'll get an error).
Even now - I was clicking through their examples one by one, and this started happening:

<img width="916" alt="Screenshot 2019-10-26 at 00 30 02" src="https://user-images.githubusercontent.com/392513/67609993-c2a8d180-f787-11e9-976d-1e8ce1876f81.png">

To me this is not reliable...
Also - if it cannot find a favicon (I checked my bookmarks and half of them are not there) - it  timeouts and returns a json error.

And if my users open their home pages and half of the bookmarks end-up looking like the picture above - I will get a ton of bug-reports that I can't fix, because it's not on my end :-)
That's why I don't want a 3rd party service.
It's a dependency that I cannot control, but am held responsible for.

There may be reliable favicon services out there, but they are costly, and this is a FOSS project 😄

**Comment by HanabishiRecca** [comment]
@tborychowski, hmm.
Technically this is possible to parse icons on the client. I can made this. But I think there will be the problem retrieving favicon via xhr (damn CORS).

**Comment by tborychowski** [comment]
exactly. I tried that too.

**Comment by HanabishiRecca** [comment]
This extension successfully overrides CORS https://addons.mozilla.org/firefox/addon/access-control-allow-origin/
I've checked inside, it contains just a few lines of code. Looks like you can easly implement such method.

**Comment by tborychowski** [comment]
1. To do that my addon would need to requests the permission "Access your data for all websites" - which is a show-stopper for many people (including myself) and I won't go there. 
2. Even if I'd do that (hack the CORS problem and parse favicons) - I would have to maintain 3 addons in 1 (start page + cors hack + favicon parser). I understand that you may not realise how much work that would be, but believe me, I do. And I cannot possibly commit that much of my time to this simple  thing.
3. You may also not realise how ridiculously difficult is to create a 99% working favicon finder (one that would work for 100% sites does not exist`*`). 
I tried to create one myself (twice: [1](https://github.com/tborychowski/favicon-service), [2](https://github.com/tborychowski/favicon-service-php)) and was not satisfied with the results. 
I also tried all other projects available in the internet, which claimed to do that - and was utterly disappointed with their results.
I spent days and weeks trying to find a decent solution (back when I was working on newtab-bookmarks) but failed.
This is the reason why I abandoned it!
And I'm not planning to go through that again. 
Sorry.
If you don't like the functionality - there are plenty of alternatives, you don't have to use this one.



`*` The only one, that has an acceptable coverage is the shitty google one that I'm using for favicons in docked folders: `https://www.google.com/s2/favicons?domain=`
Unfortunately it  only provides 16x16px icons.

**Comment by HanabishiRecca** [comment]
I realise. Ok then.
Even just url will be very convenient. Actually the point was to batch set up all thumbnails. So do it manually not too hard.

**Comment by tborychowski** [comment]
yeah, batch setting is another monster to tackle... I'm thinking about it :-)

Anyway, setting URL for thumbnail was just released :-)

**Comment by Natetronn** [comment]
I recently built an extension for personal use. It has tabs and all_urls permission turned on. I'm not planning on releasing it and only use it on my home machine. 

It grabs each tab, its URL and places them all into a new tab/page. I also grab each tab's favicon and capture a screenshot using [tabs.captureTab()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab) and then display it all in cards. It's similar to your extension in layout.

Before I realized I could captureTab() I was looking into using [html2canvas](https://html2canvas.hertzen.com/). I saw some articles where people were able to grab screenshot from URL. If I remember correctly they used an iframe trick to do it. Not sure it's a good idea, what risk is involved with using something like that etc. but, thought I'd share, just the same.

P.s. I found your extension over on one of the svlete sites. It's really cool how you made this with svelte. Thanks!

https://github.com/perfect-things/perfect-home/issues/89

**Comment by tborychowski** [comment]
Hi,
Thanks for that. 
Svelte is the only framework worth using IMO (and I've tested them all), with which you actually write less code than with vanilla JS, and which does not require you to learn some weird & creepy language on top of the web technologies.
I've been using it since before it was released (and called Ractive) and it seems people starting to realise that, as it landed as 4th (or was it 3rd?) most popular framework in GH without the marketing & support from a big corporations!
Out of curiosity can you tell me which of the svelte sites was it?

Regarding the extension & screen/icon grabbing: 
- html2canvas is shit. It only works for static pages with basic content. Anything more complex, js-generated UIs won't work
- `captureTab` is cool, but very slow: you need to open a new tab, screengrab it and then close it. (when I tested that - creating hidden tabs didn't work) so with a 100 bookmarks - it will freeze your browser for a while.
- Most importantly, however, this requires `all_urls` permissions, which people (myself included) are not comfortable.

**Comment by Natetronn** [comment]
@tborychowski thanks for the reply, Tom! 

I've never used html2canvas before. I only stumbled upon it in my research. And I did want to mention it, as I recently was researching all this stuff. Of course, you're way ahead of me in this game at this point so, it figures that you already knew about it. Glad I didn't go down that road, as it was hacky, either way.

You're right about captureTab. It's fairly slow. I wonder if it has something to do with generating it in base64? I don't know. 

I found your extension over on Made With Svelte:  https://madewithsvelte.com/perfect-home

Good stuff...(svelte) And you're right, the syntax makes so much more sense and isn't so, dare I say, spaghetti-fied lol
