### ISSUE TITLE
Suggestions to use perfect-home as a media center

### ISSUE THREAD

**Issue by mahibi** [perfect-things/perfect-home#52]
I finally found this addon to create the "media-center" i always wanted.
I set the tile size to 390/180 and changed the css to this:
```
.bookmarks .item-folder .item-thumb {
    mask: none;
}

.bookmarks .item-title {
    display: block;
    padding: 0;
    margin-top: -140px;
    max-height: 2.3em;
    overflow: hidden;
    text-overflow: ellipsis;
    font-weight: bold;
    color: white;
    font-size: 30px;
    text-shadow: 3px 3px 3px #000;
}

.bookmarks .item-thumb {
    font: 0 px;
}
```
This leads to a large view of my media links so i can click them with a wireless mouse from my couch (I actually stopped to use my FireTV-Stick since then).

1) However, i don't want to see my media-links on the new-tab page when i work at my PC.
I would like to have a seperate Button that loads my "media center". There is no need for me that it is the new-tab page. Is there any possibility for this?

2) I guess that something like a media center theme would be quite popular, so there could be some predefined css styles to choose from?

Both features (seperate button to open the media center and an optimized css style) could even be the base for a media center app based on perfect-home.

**Comment by tborychowski** [comment]
Thanks for that. I'll definitely consider these features.
I need to rewrite/simplify the grid layout first (there are too many complex rules, that do not scale well).

**Comment by tborychowski** [comment]
Hello again.
I've spent some time thinking about your ideas, and have created 2 separate issues for them (linked above).

Both are great ideas and I was thinking about something similar, but didn't realise that it would actually be useful to anyone :-)
Also, both tasks are complex and time consuming, so it will take a bit of time to do properly.

Lastly, for your `.bookmarks .item-title` style, you may need `white-space: nowrap;` rule, as otherwise the ellipsis may not work :-)

I'm closing this issue, as the further progress will be tracked in #53 & #54.

**Comment by tborychowski** [comment]
One more thing: have you considered multiple profiles?
This way you'd have a separation between your TV and PC with different bookmarks, layouts, styles, etc.

**Comment by mahibi** [comment]
Hi,
thanks  for the advice, but multiple browser-profiles won't work for me because i would like to be able to add media bookmarks to the media folder even when i work on my pc. 
I'll just wait for #53 & #54 ;-) thank you
