### ISSUE TITLE
Breaks duplicate tab feature when using the address bar to navigate from Perfect Home page

### ISSUE THREAD

**Issue by g-fb** [perfect-things/perfect-home#80]
1. Open new tab (Perfect Home page)
2. Navigate with address bar to example.com
3. Go to a different page in the same tab, clicking a link, bookmark etc.
4. Duplicate the tab
5. The new tab loads example.com

Firefox 74.0
Perfect Home 0.9.0

**Comment by tborychowski** [comment]
Hi,
Thanks for your contribution.

This looks like a Firefox bug: my add-on only controls what's displayed in the add-on page.
It doesn't affect "duplicate tab" or "address bar" in any way.
(if you look at the permissions the add-on requires - address bar & tabs is not even on the list, so it doesn't have access to them at all!)

Why do you think this is caused by the _Perfect Home_ add-on?

**Comment by g-fb** [comment]
It only happens when Perfect Home is enabled.

**Comment by tborychowski** [comment]
I'll have a deeper dive

**Comment by tborychowski** [comment]
After thorough testing I was able to pin-point that to 1 setting in the `manifest.json` of the extension: 
```js
	"chrome_url_overrides": {
		"newtab": "index.html"
	},
```
If I don't override a `newtab` - this doesn't happen.
If I override it (even with an empty `index.html`) - this happens.
It also happens for any other firefox extension (tested a couple of them) that overrides a new tab.
What actually happens is the new tab is opened with the correct address, but then the tab is immediately redirected to some base URL of the parent tab (very weird).
So if you click "Back" button - you'd get to the correct address.

So, tl;dr: firefox bug!
