### ISSUE TITLE
Option to Remove/Hide the "Extension...ect Home" 

### ISSUE THREAD

**Issue by Cheeseman4** [perfect-things/perfect-home#90]
Tom,

Thanks for a great add-on. I would like to request an option to remove/hide the "Extension...ect Home" text that clutters the search bar on the Bookmark/new tab page.

I hope this is the right place to make suggestions. I hope to see this addition soon. I'm not too tech savvy, so I might have overlooked a way to do this myself.

Colby

**Comment by tborychowski** [comment]
Hi Colby,
Thank you for the feedback. 
I understand your issue very well and share the opinion. 
Unfortunately it's not possible to do. This is firefox'es built-in behaviour that they do not allow to change from the extension. 
This might only be possible to do manually from the userScript overrides but not from an extension. 
Unless you have seen another extension that does that, and I'm missing something?

**Comment by tborychowski** [comment]
feel free to reopen the issue if you have further information.

**Comment by cengels** [comment]
Hi, I just thought I'd chime in here since there _is_ supposedly a way to hide that notice, though I haven't managed to get it to work myself. You have to create a [userChrome.css](https://www.userchrome.org/) file (basically a way to add custom styling to the browser itself) and then add the following lines, taken from [this reddit thread](https://www.reddit.com/r/firefox/comments/8s5dkp/any_way_to_permanently_hide_this_extension/):

```
#identity-box:not(:hover) #identity-icon-label {
    display:none;
}
```

Be aware that this will hide the icon label for any extension though (if it works at all; those posts are almost two years old, so there's a chance the elements have been renamed since then). If you only want to hide Perfect Home, you could try `#identity-icon-label[value="Extension (Perfect Home)"]` instead.

Just to clarify: this is something you, the user, have to do yourself. As an extension creator, you can't automate this process for security reasons (otherwise it would open extensions up to hijack the new tab page without the user's knowledge).
