### ISSUE TITLE
Question: effect

### ISSUE THREAD

**Issue by Vldm11r** [perfect-things/perfect-home#92]
How to apply this effect to other bookmarks and folders.
![GitHub Logo](https://i.imgur.com/8UOYOCm.gif)

```
img, a[href*='photo-'], span[style*='image: url'], a[style*='image: url'], div[style*='image: url'] {
  filter: opacity(0.5) ;
  transition:0.6s;
}

img :hover, a[href*='photo-']:hover, span[style*='image: url']:hover, a[style*='image: url']:hover, div[style*='image: url']:hover   {
  filter:opacity(0.9);
  transition:0.1s;
}
```

It doesn’t work out for me to apply this to one standard bookmark or folder...

**Comment by tborychowski** [comment]
I think you use the wrong selectors. All bookmarks and folders have the same class (`item`) that you can use. E.g.:
```css
.bookmarks .item { 
  filter: none;
  opacity: 0.5; 
  transition: opacity .6s ease-out; 
}

.bookmarks .item:hover { opacity: 0.9; }
```
- you need to use `.bookmark .item` to have the high enough specificity to override the default css
- you don't need to use `filter` to animate the `opacity` - you can just use `opacity` (`filter: opacity()` has some valid use cases, but is not needed here).
- first you need to remove the original `filter` if you don't want the `drop-shadow` (set in the default css)
- then set the `opacity` to `0.5` and the `transition` to animate on the opacity only (as otherwise it will animate all properties, which is not needed)
- lastly - just need to change the `opacity` on `hover`

**Comment by tborychowski** [comment]
If that works, I'm closing the issue. Feel free to reopen if you have more questions/issues :-)
